version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  cassandra:
    image: 'cassandra:latest'
    container_name: cassandra
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_CLUSTER_NAME=WeatherDataCluster
    volumes:
      - cassandra_data:/var/lib/cassandra
  python:
    build: ./myapp
    container_name: python
    ports:
      - '5000:5000'
    environment:
      - KAFKA_SERVER=kafka:9092
      - CASSANDRA_SERVER=cassandra:9042
    depends_on:
      - kafka
      - cassandra
    volumes:
      - ./myapp:/app
volumes:
  cassandra_data:

